//! Activity-checked direct keyboard events and retirement of seat input.

use crate::{InputError, Server};
use smithay::backend::input::KeyState;

/// One trusted evdev transition, never accepted from agent IPC.
#[derive(Debug, Clone, Copy)]
pub struct DirectKeyEvent {
    /// Linux evdev code, without XKB's offset.
    pub code: u32,
    /// Press or release; repeats are generated by clients.
    pub state: KeyState,
    /// Monotonic milliseconds.
    pub time: u32,
}

impl Server {
    /// Route a key only while the trusted direct backend reports an active seat.
    ///
    /// Inactive calls discard even malformed queued events, release held keys,
    /// dismiss popup grabs and clear keyboard focus. Call with `None` on keyboard
    /// removal or pause. Active calls never choose focus: trusted shell policy
    /// must explicitly restore it. Duplicate presses and unmatched releases do
    /// not deliver input or authorize popups. Invalid active codes preserve state.
    ///
    /// This does not acquire devices or poll session activity. Do not mix nested
    /// and direct drivers on one seat. Use `clear_input` when the whole seat stops.
    pub fn direct_keyboard(
        &mut self,
        active: bool,
        event: Option<DirectKeyEvent>,
    ) -> Result<bool, InputError> {
        if self.surfaces.keyboard.is_none() {
            return Err(InputError::Unavailable);
        }
        if !active {
            self.keyboard_focus(None)?;
            return Ok(false);
        }
        match event {
            Some(event) => self.keyboard_key(event.code, event.state, event.time),
            None => Ok(false),
        }
    }

    /// Release held input and dismiss grabs before retiring a direct output.
    ///
    /// Missing capabilities are harmless. Existing cleanup sends matched releases
    /// and leaves, resets depressed modifiers and invalidates initiating serials.
    /// Repeated cleanup cannot release a key/button twice. Events are queued;
    /// the caller must flush or dispatch to deliver them to connected clients.
    /// This clears routing, not device authority: the backend must stop feeding
    /// events until active again, then explicitly restore keyboard focus and
    /// supply fresh pointer motion. No device is opened or closed here.
    /// Native control presses are disarmed, retaining their release ownership.
    pub fn clear_input(&mut self) {
        self.cancel_window_control();
        // These operations can only refuse an absent capability, intentionally
        // allowed for a display without input or with a keyboard-only seat.
        let _ = self.keyboard_focus(None);
        let _ = self.surfaces.clear_pointer();
    }
}
