//! Trusted backend keyboard routing, separate from surface protocol lifetimes.

use crate::{Server, surfaces::Surfaces};
use smithay::{
    backend::input::KeyState,
    delegate_seat,
    input::{
        Seat,
        keyboard::{FilterResult, KeyboardHandle, Keycode, XkbConfig},
    },
    reexports::wayland_server::protocol::wl_surface::WlSurface,
    utils::{SERIAL_COUNTER, Serial},
};

/// Refusal at the compositor's internal input boundary, never an agent verb.
#[derive(Debug, thiserror::Error)]
pub enum InputError {
    /// Private display initialization failed.
    #[error(transparent)]
    Socket(#[from] crate::SocketError),
    /// The requested XKB configuration could not be compiled.
    #[error("keyboard initialization failed: {0}")]
    Keymap(String),
    /// This display was created without a keyboard backend.
    #[error("keyboard is not enabled")]
    Unavailable,
    /// Only this display's live, mapped toplevels may receive keyboard focus.
    #[error("keyboard focus target is not a mapped toplevel")]
    Unmapped,
    /// Linux evdev keyboard codes are bounded and zero is reserved.
    #[error("invalid evdev key code")]
    InvalidKey,
    /// Pointer routing was not enabled on this display's seat.
    #[error("pointer is not enabled")]
    PointerUnavailable,
    /// Nonfinite or out-of-range pointer coordinates, scroll or button code.
    #[error("invalid pointer input")]
    InvalidPointer,
}

/// The seat owns its protocol resources; the cloned handle drives XKB state.
pub(crate) struct Keyboard {
    /// Shared seat for keyboard and optional pointer capability.
    pub(crate) seat: Seat<Surfaces>,
    /// Keyboard handle with the person's configured layout.
    pub(crate) handle: KeyboardHandle<Surfaces>,
    /// Last accepted timestamp, reused for releases synthesized on focus loss.
    pub(crate) time: u32,
    /// The keys a client was actually told about, which is not every key held.
    ///
    /// **The shell tracks keys with nothing focused, so *pressed* means two
    /// things and they have to be kept apart.** `KeyboardHandle::pressed_keys`
    /// is every key physically down, which is what this compositor reads its own
    /// modifiers from; this is the subset some client was sent, which is what
    /// *is a client holding this* means. Smithay draws the same distinction and
    /// keeps its `forwarded_pressed_keys` `pub(crate)`, so this is that set,
    /// kept here because two questions that used to have one answer now have
    /// two.
    pub(crate) forwarded: std::collections::HashSet<Keycode>,
    /// Latest delivered real key event; consumed by popup initiation, never synthesized.
    pub(crate) popup_key: Option<(Serial, WlSurface)>,
}

impl Keyboard {
    /// Native name opening must not acquire application modifier chords.
    ///
    /// Asked of the **forwarded** set: a chord held over empty canvas belongs to
    /// no application, so there is nothing to acquire it from.
    pub(crate) fn has_pressed_keys(&self) -> bool {
        !self.forwarded.is_empty()
    }

    /// Whether a valid evdev key is already owned by ordinary client routing.
    ///
    /// The forwarded set for the same reason: a key no client was told about is
    /// not one ordinary client routing owns.
    pub(crate) fn client_holds(&self, code: u32) -> bool {
        self.forwarded.contains(&(code + 8).into())
    }
}

impl Server {
    /// Bind a display with a keyboard seat and an explicitly supplied XKB layout.
    ///
    /// Invalid keymaps tear down the whole new display, including its socket.
    /// Repeat is generated by clients (25 Hz after 600 ms), never by the backend.
    /// These are initial backend defaults; person-owned settings remain separate.
    pub fn bind_keyboard(
        runtime: &std::path::Path,
        name: &str,
        config: XkbConfig<'_>,
    ) -> Result<Self, InputError> {
        let mut server = Self::bind(runtime, name)?;
        let display = server.display_handle();
        let mut seat = server.surfaces.seats.new_wl_seat(&display, "alo-seat");
        let handle = seat
            .add_keyboard(config, 600, 25)
            .map_err(|error| InputError::Keymap(error.to_string()))?;
        server.surfaces.keyboard = Some(Keyboard {
            seat,
            handle,
            time: 0,
            popup_key: None,
            forwarded: std::collections::HashSet::new(),
        });
        Ok(server)
    }

    /// Set focus from trusted shell policy, refusing foreign, dead or unmapped roots.
    ///
    /// Clearing or changing focus releases held keys before leave, so a new
    /// application cannot inherit a key pressed for another application.
    /// XDG activated state follows the resulting keyboard owner, without raising.
    /// Selecting a grabbed popup's root preserves the topmost popup's focus;
    /// clearing focus or selecting another root dismisses the grab chain.
    pub fn keyboard_focus(&mut self, surface: Option<&WlSurface>) -> Result<(), InputError> {
        if surface.is_some_and(|surface| !self.mapped_surfaces().any(|root| root == surface)) {
            return Err(InputError::Unmapped);
        }
        if self.surfaces.keyboard.is_none() {
            return Err(InputError::Unavailable);
        }
        if let Some(grab) = &self.surfaces.popup_grab {
            if surface == Some(&grab.root) {
                return Ok(());
            }
            self.surfaces.dismiss_popup_grab();
        }
        self.surfaces.set_keyboard_focus(surface.cloned())
    }

    /// Route a Linux evdev key from a trusted backend, adding XKB's offset once.
    ///
    /// Returns false for no focus, duplicate presses or unmatched releases —
    /// the answer is *was a client told*, which is why no focus is still false.
    ///
    /// **A key is remembered whether or not anything is focused, and this used to
    /// say the opposite.** The shell's own modifier state comes from XKB, XKB is
    /// only advanced by handling the key, and handling was skipped when
    /// `current_focus()` was `None` — so on a canvas with no window focused,
    /// holding Ctrl changed nothing the compositor could read and Ctrl+wheel
    /// panned instead of zooming. A compositor has to know what is held in order
    /// to answer for its own gestures; only *forwarding* depends on focus.
    ///
    /// So the key always reaches XKB and reaches a client only when one is
    /// focused, and [`Keyboard::forwarded`] is what separates the two questions.
    /// Call with monotonic milliseconds.
    /// The latest delivered press or release may initiate a popup on its focused parent;
    /// another accepted key event, a focus change or a successful grab invalidates
    /// that serial. Synthetic focus-cleanup events cannot initiate. Only matched
    /// releases are delivered, so a release without a real held key cannot authorize.
    pub fn keyboard_key(
        &mut self,
        code: u32,
        state: KeyState,
        time: u32,
    ) -> Result<bool, InputError> {
        if !(1..=0x2ff).contains(&code) {
            return Err(InputError::InvalidKey);
        }
        self.surfaces.prune_keyboard_focus();
        let keyboard = self
            .surfaces
            .keyboard
            .as_ref()
            .ok_or(InputError::Unavailable)?
            .handle
            .clone();
        let code: Keycode = (code + 8).into();
        if keyboard.pressed_keys().contains(&code) == (state == KeyState::Pressed) {
            return Ok(false);
        }
        let serial = SERIAL_COUNTER.next_serial();
        let focus = keyboard.current_focus();
        // Intercepting still advances XKB — `input_intercept` records the key and
        // updates the modifiers before the filter is consulted — so with nothing
        // focused the key is known to this compositor and sent to nobody.
        keyboard.input::<(), _>(&mut self.surfaces, code, state, serial, time, |_, _, _| {
            if focus.is_some() {
                FilterResult::Forward
            } else {
                FilterResult::Intercept(())
            }
        });
        if let Some(keyboard) = self.surfaces.keyboard.as_mut() {
            keyboard.time = time;
            keyboard.popup_key = focus.as_ref().map(|surface| (serial, surface.clone()));
            if focus.is_some() {
                match state {
                    KeyState::Pressed => keyboard.forwarded.insert(code),
                    KeyState::Released => keyboard.forwarded.remove(&code),
                };
            }
        }
        Ok(focus.is_some())
    }
}

impl Surfaces {
    /// Actual keyboard owner expressed as a toplevel, including a grabbed popup.
    pub(crate) fn keyboard_root(&self) -> Option<WlSurface> {
        let focus = self.keyboard.as_ref()?.handle.current_focus()?;
        if self.mapped_toplevel(&focus).is_some() {
            Some(focus)
        } else {
            self.popup_grab.as_ref().and_then(|grab| {
                (self.popup_keyboard_focus().as_ref() == Some(&focus)).then(|| grab.root.clone())
            })
        }
    }

    /// Remove focus immediately after processing unmap/destruction/disconnect.
    pub(crate) fn prune_keyboard_focus(&mut self) {
        let focus = self
            .keyboard
            .as_ref()
            .and_then(|keyboard| keyboard.handle.current_focus());
        if focus.is_some_and(|surface| {
            !self.mapped().any(|root| *root == surface)
                && self.popup_keyboard_focus().as_ref() != Some(&surface)
        }) {
            let _ = self.set_keyboard_focus(None);
        }
    }

    /// Release the keys a client was told about before switching recipients.
    ///
    /// **Only the forwarded ones, and only in the client.** This released every
    /// key XKB had down, which was the same set while nothing was tracked
    /// unfocused. It is not the same set any more: somebody holding Ctrl over
    /// empty canvas and then focusing a window would have had Ctrl released
    /// underneath their own finger, and the shell would have read no modifier
    /// until they let go and pressed again.
    ///
    /// A key can only be *stuck* in a client that was told it went down, so the
    /// forwarded set is exactly the set that needs releasing — and it is released
    /// with `input_forward`, which tells the client without touching XKB, so what
    /// is physically held stays held.
    pub(crate) fn set_keyboard_focus(
        &mut self,
        focus: Option<WlSurface>,
    ) -> Result<(), InputError> {
        let keyboard = self.keyboard.as_ref().ok_or(InputError::Unavailable)?;
        let handle = keyboard.handle.clone();
        let time = keyboard.time;
        if handle.current_focus() == focus {
            return Ok(());
        }
        if let Some(keyboard) = self.keyboard.as_mut() {
            keyboard.popup_key = None;
        }
        let forwarded: Vec<_> = self
            .keyboard
            .as_ref()
            .map(|keyboard| keyboard.forwarded.iter().copied().collect())
            .unwrap_or_default();
        for code in forwarded {
            handle.input_forward(
                self,
                code,
                KeyState::Released,
                SERIAL_COUNTER.next_serial(),
                time,
                false,
            );
        }
        if let Some(keyboard) = self.keyboard.as_mut() {
            keyboard.forwarded.clear();
        }
        handle.set_focus(self, focus, SERIAL_COUNTER.next_serial());
        // Smithay 0.7 notifies SeatHandler on entry/replacement, but not clearing.
        // Observe the resulting focus here so backend and lifecycle loss agree.
        self.configure_activation(handle.current_focus().as_ref());
        Ok(())
    }
}

delegate_seat!(Surfaces);
