//! Trusted backend keyboard routing, separate from surface protocol lifetimes.

use crate::{Server, surfaces::Surfaces};
use smithay::{
    backend::input::KeyState,
    delegate_seat,
    input::{
        Seat,
        keyboard::{FilterResult, KeyboardHandle, XkbConfig},
    },
    reexports::wayland_server::protocol::wl_surface::WlSurface,
    utils::SERIAL_COUNTER,
};

/// Refusal at the compositor's internal input boundary, never an agent verb.
#[derive(Debug, thiserror::Error)]
pub enum InputError {
    /// Private display initialization failed.
    #[error(transparent)]
    Socket(#[from] crate::SocketError),
    /// The requested XKB configuration could not be compiled.
    #[error("keyboard initialization failed: {0}")]
    Keymap(String),
    /// This display was created without a keyboard backend.
    #[error("keyboard is not enabled")]
    Unavailable,
    /// Only this display's live, mapped toplevels may receive keyboard focus.
    #[error("keyboard focus target is not a mapped toplevel")]
    Unmapped,
    /// Linux evdev keyboard codes are bounded and zero is reserved.
    #[error("invalid evdev key code")]
    InvalidKey,
}

/// The seat owns its protocol resources; the cloned handle drives XKB state.
pub(crate) struct Keyboard {
    /// Keep the seat available for the subsequent pointer component.
    pub(crate) _seat: Seat<Surfaces>,
    /// Keyboard handle with the person's configured layout.
    handle: KeyboardHandle<Surfaces>,
    /// Last accepted timestamp, reused for releases synthesized on focus loss.
    time: u32,
}

impl Server {
    /// Bind a display with a keyboard seat and an explicitly supplied XKB layout.
    ///
    /// Invalid keymaps tear down the whole new display, including its socket.
    /// Repeat is generated by clients (25 Hz after 600 ms), never by the backend.
    /// These are initial backend defaults; person-owned settings remain separate.
    pub fn bind_keyboard(
        runtime: &std::path::Path,
        name: &str,
        config: XkbConfig<'_>,
    ) -> Result<Self, InputError> {
        let mut server = Self::bind(runtime, name)?;
        let display = server.display_handle();
        let mut seat = server.surfaces.seats.new_wl_seat(&display, "alo-seat");
        let handle = seat
            .add_keyboard(config, 600, 25)
            .map_err(|error| InputError::Keymap(error.to_string()))?;
        server.surfaces.keyboard = Some(Keyboard {
            _seat: seat,
            handle,
            time: 0,
        });
        Ok(server)
    }

    /// Set focus from trusted shell policy, refusing foreign, dead or unmapped roots.
    ///
    /// Clearing or changing focus releases held keys before leave, so a new
    /// application cannot inherit a key pressed for another application.
    pub fn keyboard_focus(&mut self, surface: Option<&WlSurface>) -> Result<(), InputError> {
        if surface.is_some_and(|surface| !self.mapped_surfaces().any(|root| root == surface)) {
            return Err(InputError::Unmapped);
        }
        self.surfaces.set_keyboard_focus(surface.cloned())
    }

    /// Route a Linux evdev key from a trusted backend, adding XKB's offset once.
    ///
    /// Returns false for no focus, duplicate presses or unmatched releases.
    /// No keys are remembered while unfocused. Call with monotonic milliseconds.
    pub fn keyboard_key(
        &mut self,
        code: u32,
        state: KeyState,
        time: u32,
    ) -> Result<bool, InputError> {
        if !(1..=0x2ff).contains(&code) {
            return Err(InputError::InvalidKey);
        }
        self.surfaces.prune_keyboard_focus();
        let keyboard = self
            .surfaces
            .keyboard
            .as_ref()
            .ok_or(InputError::Unavailable)?
            .handle
            .clone();
        if keyboard.current_focus().is_none() {
            return Ok(false);
        }
        let code = (code + 8).into();
        if keyboard.pressed_keys().contains(&code) == (state == KeyState::Pressed) {
            return Ok(false);
        }
        keyboard.input::<(), _>(
            &mut self.surfaces,
            code,
            state,
            SERIAL_COUNTER.next_serial(),
            time,
            |_, _, _| FilterResult::Forward,
        );
        if let Some(keyboard) = self.surfaces.keyboard.as_mut() {
            keyboard.time = time;
        }
        Ok(true)
    }
}

impl Surfaces {
    /// Remove focus immediately after processing unmap/destruction/disconnect.
    pub(crate) fn prune_keyboard_focus(&mut self) {
        let focus = self
            .keyboard
            .as_ref()
            .and_then(|keyboard| keyboard.handle.current_focus());
        if focus.is_some_and(|surface| !self.mapped().any(|root| *root == surface)) {
            let _ = self.set_keyboard_focus(None);
        }
    }

    /// Release pressed keys using the same XKB path before switching recipients.
    fn set_keyboard_focus(&mut self, focus: Option<WlSurface>) -> Result<(), InputError> {
        let keyboard = self.keyboard.as_ref().ok_or(InputError::Unavailable)?;
        let handle = keyboard.handle.clone();
        let time = keyboard.time;
        if handle.current_focus() == focus {
            return Ok(());
        }
        for code in handle.pressed_keys() {
            handle.input::<(), _>(
                self,
                code,
                KeyState::Released,
                SERIAL_COUNTER.next_serial(),
                time,
                |_, _, _| FilterResult::Forward,
            );
        }
        handle.set_focus(self, focus, SERIAL_COUNTER.next_serial());
        Ok(())
    }
}

delegate_seat!(Surfaces);
